### PR TITLE
CAM-9992 feat(DMN 1.2): add DMN 1.2 namespace and migrate test models

### PR DESCRIPTION
**Pull request by falko**
DMN 1.2 has been adopted by OMG and released to the public in January 2019. This pull request adds the support for the DMN 1.2 namespace, i.e. it allows DMN 1.2 models that use the DMN 1.1 to be parsed and edited. Currently, all DMN 1.2 models will be rejected by the parser. Having the namespace support will allow Camunda to participate in the DMN TCK again.

It is out of scope for this pull request to implement support for the new language features added in DMN 1.2.

### CODE REVIEW

**Comment by falko** [comment]
The tests are still failing, but I thought, I'd already push the code to a branch and start the pull request.

**Comment by tmetzke** [comment]
Hi Falko,

thanks for the work on this!
We'll look into it as soon as possible and track the progress as well in https://app.camunda.com/jira/browse/CAM-9992.

Best,
Tobias

**Comment by ThorbenLindhauer** [comment]
Hi Falko,

Can you please add a brief description to your pull request about what it achieves?

You mention the code is not finished yet. Would you already like to get feedback on anything? If not, we will just wait until you are done.

Cheers,
Thorben

**Comment by falko** [comment]
Hi Thorben,

this pull request allows the API to parse (and the Camunda engine to 
run) DMN 1.2 models that are using the DMN 1.1 feature set. Without 
this, any models from a DMN 1.2 modeling tool will be rejected as invalid.

This is an important precondition to starting any DMN 1.2 work in the 
Camunda Modeler, because without support for the namespace in the 
engine, the Modeler cannot be touched.

The DMN model API is already nicely designed to support multiple 
namespaces, so it was very easy to add an additional one. So the 
implementation is complete.

I probably just went a little too far (given my available time to work 
on this) by also migrating the tests to 1.2. We should probably revert 
these test changes and simply take the additional namespace in.

Please, lets try to get this into the Camunda 7.11 release. Otherwhise 
we will loose another 6 months until any DMN 1.2 work on the modeler and 
in Philipp's DMN Scala Engine can be started.

Greetings from Hannover,
Falko

**Comment by ThorbenLindhauer** [comment]
Hi Falko,

Thanks for the clarification. Is DMN 1.2 fully backwards compatible with 1.1 or are some 1.1 models no longer spec-compliant in 1.2?

Besides, our code freeze for 7.11.0 is next Thursday. We will try to review and merge your PR until then, but can't promise it.

Cheers,
Thorben

**Comment by falko** [comment]
Hi Thorben,

yes, DMN 1.2 is backwards compatible. Okay, if the deadline is that 
close let me know if I can help somewhere.

Cheers,
Falko

**Comment by ThorbenLindhauer** [comment]
Hi Falko,

It would be great if you could do the following:

* Revert the namespace changes to the existing DMN models in the test suite
* Add a dedicated test case that parses a DMN model in the DMN 1.2 namespace
* Add a test case to `camunda-engine-dmn` that evaluates a DMN table in the 1.2 namespace

Cheers,
Thorben

**Comment by falko** [comment]
I reverted the namespace changes to the existing DMN models in the test suite and will now work on adding a dedicated test case that parses a DMN model in the DMN 1.2 namespace similar to the `ExampleTestCompatibility`

**Comment by falko** [comment]
Is it on purpose that this test class is not run regularly?
[ExampleTestCompatibility](https://github.com/camunda/camunda-dmn-model/blob/master/src/test/java/org/camunda/bpm/model/dmn/ExampleTestCompatibility.java)
It seems to contain tests for the support of different namespaces but `maven test` does not pick it up because the class name does not end on 'Test'. It fails for me on OpenJDK 11. However, it sounds like the perfect candidate to add the test for the DMN 1.2 namespace

**Comment by ThorbenLindhauer** [comment]
> Is it on purpose that this test class is not run regularly?

I don't think it's on purpose. Please rename the test class. We can look into any failures that you didn't introduce with the new code.

**Comment by falko** [comment]
That test case revealed, that the current implementation supports only one alternative namespace. I will have to look into a more generic solution tomorrow.

**Comment by falko** [comment]
[ModelImpl.declareAlternativeNamespace()](https://github.com/camunda/camunda-xml-model/blob/master/src/main/java/org/camunda/bpm/model/xml/impl/ModelImpl.java#L62) prevents us from registering the DMN 1.2 namespace as another alternative to the DMN 1.1 namespace in [Dmn.java](https://github.com/camunda/camunda-dmn-model/blob/master/src/main/java/org/camunda/bpm/model/dmn/Dmn.java#L220).

I see two options:
1. A quick win would be to drop support for the old alternative DMN 1.1 namespace and set the DMN 1.2 namespace as the new alternative. That is an easy change but would assume that all users have by now fixed their models to work with the correct DMN 1.1 namespace. If not they would be forced to do this now.
2. We properly design for supporting multiple DMN namespaces. This would be more future proof especially since DMN 1.3 will be finished soon and comes with a new namespace again. The risk here would be to not finish it until tomorrow.

**Comment by ThorbenLindhauer** [comment]
As option 1 breaks backwards compatibility we shouldn't go for it. Especially when you think that old models are probably still deployed in a lot of databases.

We should aim for option 2. I'm aware that this can mean we won't be able to ship this with 7.11, but we will have to accept that then. I can try to give it a shot as well, just let me know.

**Comment by falko** [comment]
@ThorbenLindhauer I pushed all my work. My last commit shows what doesn't work. For option 2 I would appreciate your help because my day filled up with meetings.

There are a couple of things that we do not have to worry about here (at least for today):
1. We should keep writing DMN 1.1 files by default.
2. If new DMN 1.2 features that are not yet supported cause exceptions of any kind, that's fine for now. The first step is to simply support the DMN 1.2 namespace for the DMN 1.1 feature set.
3. Since DMN 1.2 is fully backward-compatible and 1.3 will be as well, there is no need to over-engineer the handling of different versions and we should rather treat all versions as the same language. We should develop namespace- and version-independent and treat the namespace as an XML detail.

**Comment by falko** [comment]
@ThorbenLindhauer I started the implementation of an [XMLUnit DifferenceEvaluator](https://github.com/xmlunit/user-guide/wiki/DifferenceEvaluator) work around this [Java 9 change](https://stackoverflow.com/questions/55853220/handling-change-in-newlines-by-xml-transformation-for-cdata-from-java-8-to-java/55899834#55899834) or [bug](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8223291): [Java9CDataIndentationDifferenceEvaluator.java](https://github.com/camunda/camunda-dmn-model/blob/dmn12/src/test/java/org/camunda/bpm/model/dmn/Java9CDataIndentationDifferenceEvaluator.java)

One comparison is still missing but should be very similar.

**Comment by ThorbenLindhauer** [comment]
Hi Falko,

Thanks for all your efforts. I'm afraid we won't be able to merge this before the 7.11.0 codefreeze. I propose we try to merge this at the beginning of 7.12 and then it will be available as 7.12.0-alpha1 at the end of June. What do you think?

Cheers,
Thorben

**Comment by falko** [comment]
Well, the implementation is done and the implications well understood: It doesn't change anything for DMN 1.1. It just adds some rudimentary support for DMN 1.2. I don't know what else to do before the merge. Ultimately, it is your call whether you as a gatekeeper feel comfortable merging it. But I don't see a problem if all DMN 1.1 based tests are green. DMN 1.2 ist just best effort for now. But it costs us 6 months until we can enforce migration in the modeler.

The test case that I discovered to be ignored by Maven and failing in Java 9+ is unrelated to DMN 1.2. It should be fixed immediately, regardless of merging the namespace.

**Comment by ThorbenLindhauer** [comment]
See https://github.com/camunda/camunda-dmn-model/commit/f5759c7068c302080e2026ea8dcce56b87e9804 for test case that was not run by surefire until now.

**Comment by ThorbenLindhauer** [comment]
I was able to work on this today and will probably finish it next week.

I noticed two changes in the DMN 1.2 schema that are strictly speaking not backwards compatible:

* For `tDefinitions`, the attribute `expressionLanguage` and `typeLanguage` have a new default value (`http://www.omg.org/spec/DMN/20180521/FEEL/`). This required some changes in the DMN engine on our side.
* `tImport` is now a sub type of `tNamedElement`, which in turn defines a required attribute `name`. I guess this will break in the model API in case a user wants to read a DMN 1.2 model and add an import element. Haven't tried it though and I'm willing to accept that as a known issue.

**Comment by ThorbenLindhauer** [comment]
I merged the PR via https://github.com/camunda/camunda-dmn-model/commit/cb821fd6136de049c82d82bd816bd35b14fdc42b. You can follow https://app.camunda.com/jira/browse/CAM-10587 for the integration with the DMN engine and process engine. Thanks for the contribution!

**Comment by falko** [comment]
Thank you for finishing this!

**Pull request closed without merging**
