### PR TITLE
Added versionTag as custom camunda attribute to decision

### PR DESCRIPTION
**Pull request by EinsZwo2012**
First effort to introduce version tag for dmn like it already exists in bpmn.
https://forum.camunda.org/t/version-tag-for-decision-tables/3579

### CODE REVIEW

**Comment by EinsZwo2012** [comment]
Related jira ticket: https://app.camunda.com/jira/browse/CAM-7852

**Comment by yanavasileva** [comment]
Hi again,

Could you please format the code following our [convention](https://github.com/camunda/camunda-bpm-platform/blob/master/CONTRIBUTING.md)?
Everything else looks fine.

Best regards,
Yana

**Comment by EinsZwo2012** [comment]
Hi Yana,

I will do the changes in the next few days. Thanks for feedback.

Best regards,

Markus

**Comment by yanavasileva** [comment]
Hello Markus,

Thank you for the pull request. I merged it with [8874fe6](https://github.com/camunda/camunda-dmn-model/commit/8874fe6c75711553550d68785affaaa646e338b0).

Best regards,
Yana

**Pull request closed without merging**
